; SOURCE\KERNEL\32RTOSKRNL\DRIVERS\VIDEO\DEFINES.inc - Macro definitions for
; 32RTOSKRNL screen driver
;      
; Licensed under the MIT License. See LICENSE file in the project root for full license information.
;
; DESCRIPTION
;     This file contains macro definitions for the 32RTOSKRNL screen driver.
;     It includes definitions for screen dimensions, colors, and other
;     related constants.
;
; AUTHORS
;     Antonako1
; 
; REVISION HISTORY
;     2025/05/21 - Antonako1
;         Created this file.
; 
; REMARKS
;     None
%ifndef SCREEN_DEFINES_INC
%define SCREEN_DEFINES_INC

COLOUR_RED   equ 0xFF0000

%endif ; SCREEN_DEFINES_INC 