; <PATH> - <ABOUT>
;      
; Licensed under the MIT License. See LICENSE file in the project root for full license information.
;
; DESCRIPTION
;     Describe
; 
; AUTHORS
;     Name(s)
; 
; REVISION HISTORY
;     yyyy/mm/dd - Name(s)
;         Description
; 
; REMARKS
;     Additional remarks, if any.
%ifndef KERNEL_INC
%define KERNEL_INC

drive_number:       db 0
%include "SOURCE/KERNEL/32RTOSKRNL/MEMORY.inc"

%endif