#ifndef PAGEFRAME_H
#define PAGEFRAME_H

#include <STD/TYPEDEF.h>

VOIDPTR KERNEL_MALLOC(U32 size);
VOID KERNEL_FREE(VOIDPTR ptr);
VOIDPTR KERNEL_CALLOC(U32 num, U32 size);
BOOLEAN KERNEL_REALLOC(VOIDPTR *addr, U32 oldSize, U32 newSize);

BOOLEAN PAGEFRAME_INIT();
U32 GET_FREE_RAM();
U32 GET_USED_RAM();
U32 GET_RESERVED_RAM();
VOIDPTR REQUEST_PAGE();
VOID RESET_PAGEINDEX();
VOID FREE_PAGE(VOIDPTR addr);
VOID FREE_PAGES(VOIDPTR addr, U32 numPages);
VOID LOCK_PAGE(VOIDPTR addr);
VOID LOCK_PAGES(VOIDPTR addr, U32 numPages);
VOID RESERVE_PAGE(VOIDPTR addr);
VOID RESERVE_PAGES(VOIDPTR addr, U32 numPages);
VOID UNRESERVE_PAGE(VOIDPTR addr);
VOID UNRESERVE_PAGES(VOIDPTR addr, U32 numPages);

#endif // PAGEFRAME_H