#ifndef PAGING_H
#define PAGING_H

#include <STD/TYPEDEF.h>

#define PAGE_PRESENT    0x1
#define PAGE_READ_WRITE 0x2
#define PAGE_PRW        (PAGE_PRESENT | PAGE_READ_WRITE)

BOOLEAN PAGING_INIT(VOID);

#endif // PAGING_H