#ifndef ERROR_H
#define ERROR_H
#include <STD/TYPEDEF.h>

typedef enum {
    ERROR_NONE = 0,

    ERROR_DOUBLE_PAGE_FREE,
    ERROR_FREEING_OF_RESERVED_PAGE,
    ERROR_FREEING_OF_LOCKED_PAGE,

    ERROR_OUT_OF_MEMORY,
    ERROR_INVALID_PARAMETER,
    ERROR_NOT_FOUND,
    ERROR_ALREADY_EXISTS,
    ERROR_IO_FAILURE,

    ERROR_UNKNOWN,
} ERROR_CODE;

void SET_ERROR_CODE(U32 code);
U32 GET_LAST_ERROR();
void CLEAR_ERROR_CODE();

#endif // ERROR_H