#ifndef PS2_KEYBOARD_H
#define PS2_KEYBOARD_H
#include "../PS2.h"

/*+++
PS/2 Keyboard Commands
---*/
#define PS2_SET_LEDS    0xED
#define PS2_ECHO        0xEE
#define PS2_GET_SCANCODE_SET 0xF0
#define PS2_SET_SCANCODE_SET 0xF0
#define PS2_IDENTIFY_KEYBOARD 0xF2
#define PS2_SET_TYPEMATIC_RATE_AND_DELAY 0xF3
#define PS2_ENABLE_SCANNING 0xF4
#define PS2_DISABLE_SCANNING 0xF5
#define PS2_SET_DEF_PARAMETERS 0xF6
#define PS2_SET_ALL_KEYS_TYPEMATIC_AUTOREPEAT 0xF7
#define PS2_SET_ALL_KEYS_MAKE_RELEASE 0xF8
#define PS2_SET_ALL_KEYS_MAKE_ONLY 0xF9
#define PS2_SET_ALL_KEYS_TYPEMATIC_AUTOREPEAT_MAKE_RELEASE 0xFA
#define PS2_SET_SPECIFIC_KEY_TYPEMATIC_AUTORELEASE 0xFB
#define PS2_SET_SPECIFIC_KEY_MAKE_RELEASE_ONLY 0xFC
#define PS2_SET_SPECIFIC_KEY_MAKE_ONLY 0xFD
#define PS2_RESEND_LAST_BYTE 0xFE
#define PS2_RESET_AND_SELF_TEST 0xFF

/*+++
PS/2 Keyboard Special Bytes
---*/
#define PS2_SPECIAL_KEYDETECT_BUFFER_ERROR1 0x00
#define PS2_SPECIAL_SELF_TEST_PASSED 0xAA
#define PS2_SPECIAL_ECHO_RESPONSE 0xEE
#define PS2_SPECIAL_ACK 0xFA // Command acknowledgment
#define PS2_SPECIAL_SELF_TEST_FAILED1 0xFC // After reset or powerup
#define PS2_SPECIAL_SELF_TEST_FAILED1 0xFD // After reset or powerup
#define PS2_SPECIAL_RESEND 0xFE // Repeat last command
#define PS2_SPECIAL_KEYDETECT_BUFFER_ERROR2 0xFF

#endif // PS2_KEYBOARD_H