SYSCALL_ENTRY(SYSCALL_UPDATE_VRAM, SYS_UPDATE_VRAM) // void(void)

// PS2 Keyboard
SYSCALL_ENTRY(SYSCALL_PS2_KEYBOARD_RESET, SYS_PS2_KEYBOARD_RESET) // void(void)
SYSCALL_ENTRY(SYSCALL_GET_CURRENT_KEY_PRESSED, SYS_GET_CURRENT_KEY_PRESSED) // KEYPRESS *(void)
SYSCALL_ENTRY(SYSCALL_GET_LAST_KEY_PRESSED, SYS_GET_LAST_KEY_PRESSED) // KEYPRESS *(void)
SYSCALL_ENTRY(SYSCALL_KEYPRESS_TO_CHARS, SYS_KEYPRESS_TO_CHARS) // U8 *(KEYPRESS *)

// Memory management
SYSCALL_ENTRY(SYSCALL_KMALLOC, SYS_KMALLOC) // void *(U32)
SYSCALL_ENTRY(SYSCALL_KFREE, SYS_KFREE) // void (void *)
SYSCALL_ENTRY(SYSCALL_KREALLOC, SYS_KREALLOC) // void *(void *, U32, U32)
SYSCALL_ENTRY(SYSCALL_KCALLOC, SYS_KCALLOC) // void *(U32, U32)
// SYSCALL_ENTRY(SYSCALL_MEMCPY, SYS_MEMCPY) // void *(void *, const void *, U32)
// SYSCALL_ENTRY(SYSCALL_MEMSET, SYS_MEMSET) // void *(void *, U8, U32)

// SYSCALL_ENTRY(SYSCALL_DRAW_ELLIPSE, SYS_DRAW_ELLIPSE)