; SOURCE/KERNEL/16-BIT-BIOS/BIOS.inc - BIOS header file
;      
; Licensed under the MIT License. See LICENSE file in the project root for full license information.
;
; DESCRIPTION
;     This file contains the BIOS header information and includes necessary files for the BIOS.
; 
; AUTHORS
;     Antonako1
; 
; REVISION HISTORY
;     2025/05/10 - Antonako1
;         - Created the file.
; 
; REMARKS
;     None

%include "SOURCE/KERNEL/16-BIT-BIOS/IO.asm"
%include "SOURCE/KERNEL/16-BIT-BIOS/ISO.asm"
%include "SOURCE/KERNEL/16-BIT-BIOS/STR.asm"